const langs={
    eng:{
        message:"Check out our new discounts for the new season!!!",
        menuText1:"Other projects",
        menuText2:"About Us",
        sayHello:"Hello",
        bannerText:"Where do you want to explore?",
        flightType1:"Round trip",
        flightType2:"One way",
        place1:"From",
        place2:"To",
        date1:"There",
        date2:"Back",
        passenger:"Passenger",
        searchText:"Search flights",
        footerText:"Powered by",
        flightStatus1:"Business",
        flightStatus2:"Economy",
        seats:"Seats left",
        offer1:"Hand luggage",
        offer2:"Baggage",
        offer3:"With reissue",
        offer4:"With refund",
        offer5:"coins",
        offerBtn:"Go to issue",
        month:"March"
    },
    uz:{
        message:"Yangi mavsum uchun yangi chegirmalarimiz bilan tanishing!!!",
        menuText1:"Boshqa loyihalarimiz",
        menuText2:"Biz haqimizda",
        sayHello:"Salom",
        bannerText:"Qayerga bormoqchisiz?",
        flightType1:"Borish va qaytish",
        flightType2:"Bir tomonlama",
        place1:"Qayerdan",
        place2:"Qayerga",
        date1:"Ketish",
        date2:"Qaytish",
        passenger:"Yo'lovchi",
        searchText:"Parvozlarni qidirish",
        footerText:"Yaratuvchi",
        flightStatus1:"Biznes",
        flightStatus2:"Ekonom",
        seats:"Qolgan joylar soni:",
        offer1:"Qo'l so'mkasi",
        offer2:"Yuk",
        offer3:"Qayta shartnoma qilish",
        offer4:"Pulni qaytarish",
        offer5:"tanga",
        offerBtn:"Shartnomaga o'tish",
        month:"Mart"
    },
    ru:{
        message:"Обратите внимание на наши новые скидки на новый сезон!!!",
        menuText1:"Другие проекты",
        menuText2:"О нас",
        sayHello:"Привет",
        bannerText:"Где вы хотите исследовать?",
        flightType1:"Туда и обратно",
        flightType2:"В одну сторону",
        place1:"От",
        place2:"К",
        date1:"Туда",
        date2:"Обратный",
        searchText:"Поиск рейсов",
        footerText:"Разработчик",
        flightStatus1:"Бизнес",
        flightStatus2:"Эконом",
        seats:"Осталось мест:",
        offer1:"Ручная кладь",
        offer2:"Багаж",
        offer3:"С переизданием",
        offer4:"С возвратом",
        offer5:"монеты",
        offerBtn:"Перейти к выпуску",
        month:"Март"
    }
}
export default langs;